### ISSUE TITLE
lanta-net.ru

### ISSUE THREAD

**Issue by chirag127** [badmojr/1Hosts#203]
retracker.lanta-net.ru in 1hosts Pro is a torrent tracker. please remove it from the list.

**Comment by badmojr** [comment]
10x. Be fixed ASAP!

**Comment by chirag127** [comment]
By the way, I just started started using the list yesterday.

**Comment by badmojr** [comment]
Welcome aboard 🎉 .
Let's make this great together, one domain @ a time!

**Comment by chirag127** [comment]
> Let's make this great together, one domain @ a time!

Ya, we can make it great, how does these lists are made? are they also the combination? can you please expand the read me section. So that I get an idea on how many FPs it can have.

**Comment by badmojr** [comment]
> > Let's make this great together, one domain @ a time!
> 

The README is very clear. You first have to test drive the lists to see which one fits your needs.
You first should start using **Lite**. It is the one that strives for balance.

Then move upwards or downwards the chain.

**Comment by chirag127** [comment]
> Then move upwards or downwards the chain, if you decide that **Lite** isn't for u.

Lite is not for me. It unblocks too many legitimate tracking domains.

And I have found some False Positives since tomorrow

img.snaptube.in # for image
static.snaptube.in # for static images like whatsapp logo
push.snaptube.app # for notifications
res.apk.vidmate.net , vapi.apk.vidmate.net # vidmate app homepage do not load .

and these were found in both Lite and Pro. So, I don't think I will get any benefit from downgrading to Lite As it seems like they have similar number of FP. Don't know if retracker.lanta-net.ru was also in Lite, was it ?

You ignored my Questions  - How does these lists are made? Are these also the combination like stefens black hosts, energised, Oisd ?

**Comment by badmojr** [comment]
> > Then move upwards or downwards the chain, if you decide that **Lite** isn't for u.
> 
> Lite is not for me. It unblocks too many legitimate tracking domains.
> 
> And I have found some False Positives since tomorrow
> 
> img.snaptube.in # for image
> static.snaptube.in # for static images like whatsapp logo
> push.snaptube.app # for notifications
> res.apk.vidmate.net , vapi.apk.vidmate.net # vidmate app homepage do not load .
> 
> and these were found in both Lite and Pro. So, I don't think I will get any benefit from downgrading to Lite As it seems like they have similar number of FP. Don't know if retracker.lanta-net.ru was also in Lite, was it ?
> 
> You ignored my Questions - How does these lists are made? Are these also the combination like stefens black hosts, energised, Oisd ?

You sure they are on Lite? i.e https://adlist.vercel.app/Lite/domains.txt
Searched & found none of them being listed.

Yes, I do use external sources to build them.
It's not verbatim though, unlike what StevenBlack does.

**Comment by chirag127** [comment]
Hmm.. may be I was searching in some pro 's mirror. Either way please remove these domains top from the Pro list.



> I do use external sources to build them.

That list of external sources is not open source? I your project not open source? I thought it to be.

**Comment by badmojr** [comment]
Done!

**Comment by chirag127** [comment]
Hmm... Does 1hosts Pro not work like other Repositories? I don't see any commit here? You forgot to mention the issue in the commit or you maintain the repository somewhere else and then push here?

**Comment by badmojr** [comment]
Here u go https://github.com/badmojr/1Hosts/commit/1500f1a79b3c899a0e87b6000d7e58970b16b18d .
Have fun 😄 !

**Comment by chirag127** [comment]
So I was write the repository is maintained somewhere else and then automatically synced from time to time?

**Comment by badmojr** [comment]
The processing happens s/where else private. It has been so since the project's inception.
Whatever ends up here are the final products of that process.
