### ISSUE TITLE
`cf.shopee.com.my` (`kingsoft34.s.llnwi.net`) needs to be allowed

### ISSUE THREAD

**Issue by cbwee** [badmojr/1Hosts#254]
1Hosts (Lite) is blocking `cf.shopee.com.my` (`kingsoft34.s.llnwi.net`).

When it is blocked, sometimes Shopee Farm and Shopee Go (under Shopee Prizes) in the Android Shopee app do not open or show an error message, this happens almost every day, but they would open as soon as I allowed it manually.

**Comment by badmojr** [comment]
Hello! 

Origin:
https://raw.githubusercontent.com/ookangzheng/blahdns/master/hosts/blacklist.txt
https://github.com/What-Zit-Tooya/Ad-Block/raw/main/Main-Blocklist/Ad-Block-HOSTS.txt

 cc: @ookangzheng , @What-Zit-Tooya

**Comment by badmojr** [comment]
Investigated the domain & found it being used for banners ads.
Let's wait for the upstream maintainers to chip in.

**Comment by What-Zit-Tooya** [comment]
I didn't block `cf.shopee.com.my` or another `shopee` domain cause it used to serve banner products. For `kingsoft34.s.llnwi.net` found on `WPS office for android` to show banner ads, recently i open it but i can not found that address, so i remove it. Should fixed.

**Comment by cbwee** [comment]
> I didn't block `cf.shopee.com.my`

I mentioned it because it was shown as `cf.shopee.com.my → kingsoft34.s.llnwi.net` in the logs of NextDNS, I don't know what this really means.

<img src="https://user-images.githubusercontent.com/34395942/134832852-2ac75fc8-c551-4c19-972e-11229ac88d20.png" width="300">

The no connection error message in Shopee disappeared as soon as I added `cf.shopee.com.my` to the allowlist, and after adding it to the allowlist, I never saw the error message again.

**Comment by badmojr** [comment]
> > I didn't block `cf.shopee.com.my`
> 
> I mentioned it because it was shown as `cf.shopee.com.my → kingsoft34.s.llnwi.net` in the logs of NextDNS, I don't know what this really means.
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/34395942/134832852-2ac75fc8-c551-4c19-972e-11229ac88d20.png">
> 
> The no connection error message in Shopee disappeared as soon as I added `cf.shopee.com.my` to the allowlist, and after adding it to the allowlist, I never saw the error message again.

That's what we refer to as a CNAME.

**Comment by badmojr** [comment]
@cbwee You getting any banner ads after whitelisting the above domains?

**Comment by cbwee** [comment]
> @cbwee You getting any banner ads after whitelisting the above domains?

No, I didn't feel any difference while using Shopee or any other apps, except that the error message in Shopee doesn't appear again.

**Comment by badmojr** [comment]
Would u please reblock the domain & share the screenshot of the error, for documental purposes?

**Comment by cbwee** [comment]
> share the screenshot of the error

Before I allowed the domains, I had already taken a screenshot.

This is the screenshot of Shopee Farm showing the error message.

 <img src="https://user-images.githubusercontent.com/34395942/135181448-8112540a-47a7-4a69-8538-25286c0876fb.jpg" width=250 />

**Comment by badmojr** [comment]
I see. Thanks!

**Comment by badmojr** [comment]
Thanks everyone! 
Fixed & Closing...

**Comment by cbwee** [comment]
> `cf.shopee.com.my.` is not CNAME to `kingsoft34.s.llnwi.net`

I do not know why, when it was still not allowed, in the NextDNS logs, sometimes `cf.shopee.com.my` was CNAME to that domain, and it was blocked by 1Hosts, sometimes it did not, and would not be blocked.
